### ISSUE TITLE
Remove unused function parameters

### ISSUE THREAD

**Issue by OperationNine** [BlockchainLabsNZ/etheal-contracts#9]
![x](https://user-images.githubusercontent.com/17868193/32812470-0b54ad1c-ca0a-11e7-92b9-c9feded44337.png)
https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealController.sol#L265

![x1](https://user-images.githubusercontent.com/17868193/32812489-2bacf8ee-ca0a-11e7-94ca-1e6908fbb00d.png)
https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealController.sol#L270

![x2](https://user-images.githubusercontent.com/17868193/32812518-54101a28-ca0a-11e7-8234-3ad41650dd75.png)
https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/EthealController.sol#L277

Resolve below by following:

![x3](https://user-images.githubusercontent.com/17868193/32812921-64769a20-ca0c-11e7-9f59-6170720a25bb.png)

**Comment by thesved** [comment]
I think this could be dangerous, since these are proxy calls, which get called from the MiniMeToken (see: https://github.com/BlockchainLabsNZ/etheal-contracts/blob/master/contracts/MiniMeToken.sol#L468), removing/changing parameters changes the bytes4(keccak256()) code of the function, so the original code will call a non-existing function of the controller.

What do you think?

**Comment by OperationNine** [comment]
Yep considering this some more, I think its actually best to leave them as is

**Comment by Janther** [comment]
Hi @thesved, 

The `bytes4(keccak256())` code for the function doesn't use parameter names, just the signature, in this case `onTransfer(address,address,uint256)`, `onApprove(address,address,uint256)`, and `proxyPayment(address)`.

By avoiding naming unused variables the compiler doesn't allocate memory for these and there is a performance improvement.

If you feel more comfortable not making this change is ok since it won't change the correctness of the code, just a small performance boost.
